version: '3'
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: veeranki2014/web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping
    - rabbitmq
  mongodb:
    image: veeranki2014/mongodb:v1
    container_name: mongodb
  catalogue:
    image: veeranki2014/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
  user:
    image: veeranki2014/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: veeranki2014/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue      
  mysql:
    image: veeranki2014/mysql:v1
    container_name: mysql
  shipping:
    image: veeranki2014/shipping:v1
    container_name: shipping
    depends_on:
    - mysql        
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment:
    image: veeranki2014/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq




  



